### ISSUE TITLE
Add support for TrackballControls 

### ISSUE THREAD

**Issue by LeoGrosjean** [janvorisek/drie#51]
Hello !

What is the complexity to add [TrackballControls](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/controls/TrackballControls.js) feature ?

I'm pretty new to Vue and JS (few days, im a python dev :) ), Im trying to understand [/dist/Controls/OrbitControls.d.ts](https://github.com/janvorisek/drie/blob/master/dist/Controls/OrbitControls.d.ts) and [/src/Controls/OrbitControls.vue](https://github.com/janvorisek/drie/blob/master/src/Controls/OrbitControls.vue)

Thank you for this projet !

**Comment by janvorisek** [comment]
Added `<TrackballControls>` with basic props. Update drie to `1.0.0-alpha-1.26` to use it.

**Comment by LeoGrosjean** [comment]
Thank you very much !
I will probably make lot of tickets eheh

**Comment by janvorisek** [comment]
Closing as resolved.
