### ISSUE TITLE
Add support for GLTFLoader

### ISSUE THREAD

**Issue by LeoGrosjean** [janvorisek/drie#55]
Adding [GLTFLoader](https://threejs.org/docs/#examples/en/loaders/GLTFLoader) feature would be a must !

Sending mesh and scene from backend is very usefull !

**Comment by janvorisek** [comment]
Added in `1.0.0-alpha-1.27`.

[See docs](https://www.drie.dev/components/Loaders/GLTFLoader) for example.

**Comment by janvorisek** [comment]
Closed as resolved.
