### ISSUE TITLE
Raycasting on Gltf

### ISSUE THREAD

**Issue by LeoGrosjean** [janvorisek/drie#58]
From the documentation it says :
>GLTFloader : 
>```<GLTFLoader>``` behaves as a ```<Group>``` containing meshes loaded from the .gltf or glb file.

But ```onClick``` or ```onMouseMove``` never get triggered !

I try also to remove ```:enableRaycasting="true" @click="onClick"```
from GLTFLoader to add it to ```<Group>```, but it's not working

Is it because all the initialisation appends before the gltf file being fetch ?

I dont know if it's an issue or an impossible use case :D

Thank you for the hard work on drie ! it should have 100k ⭐ 

```vue
<template>
  <div class="example-with-props">
    <div class="example" style="width: 40vh; height: 40vh;">
      <Renderer ref="renderer" :antialias="true" resize="window">
        <PerspectiveCamera ref="camera" :position="[3, 3, 5]" :up="[0, 0, 1]" :far="200000">
          <TrackballControls :rotate-speed="0.01" :pan-speed="0.003"/>
        </PerspectiveCamera>
        <Scene>
          <AmbientLight ref="light" />
          <!--<Group >-->
            <GLTFLoader
                :enableRaycasting="true" @click="onClick"
                url='/test-mesh/'
                @load="onCreation"
                @mousemove="onMouseMove"
            >
            </GLTFLoader>
            <!--</Group>-->

            <AxesHelper :size="30"/>
        </Scene>
      </Renderer>
    </div>
  </div>
</template>

<script>
import {Renderer} from "@janvorisek/drie";
import {Scene} from "@janvorisek/drie";
import {GLTFLoader} from "@janvorisek/drie"
import {PerspectiveCamera} from "@janvorisek/drie"
import {TrackballControls} from "@janvorisek/drie"
import {AmbientLight } from "@janvorisek/drie"
import {reactive, defineComponent} from "vue";

export default defineComponent({
  name: "AddFile",
  components: {
    Renderer,
    Scene,
    GLTFLoader,
    PerspectiveCamera,
    TrackballControls,
    AmbientLight ,
  },
  props: {
  },
  data() {
  },
  mounted() {
  },
  methods: {
    onClick(group) {
      console.log(group)
    },
    onCreation(group) {
      console.log("gltf has been loaded")
    },
    onMouseMove(is) {
      console.log(is); // Do whatever you need to with is
    }
  },

});

</script>

<style>
</style>`
```

PS: I'm trying to figure out your documentation so I can contribute a bit

**Comment by janvorisek** [comment]
Thanks for reporting! I just forgot to use the magic `manageParentRelationship` in the GLTF and OBJ Loaders.

I tested `click` on GLTF and it works for me. Can you test all the events in your project? There may be another issues.

Note that `onClick` argument should be `is` too and not group (See [`Intersection` interface](https://www.drie.dev/raycasting#intersection-interface). You can get the intersected `Object3D` using `is[0].object`.

Regarding the docs - most of it is autogenerated from source (props, events) and the rest contained in the `<docs></docs>` block of the `.vue` SFC. I need to add some tutorial on how to `docs:dev` and `docs:build`. It's a bit hacky now :)

I'll also add a guide on how to implement new components, but the library doesn't seem mature enough. I'm changing the internals all the time.

**Comment by LeoGrosjean** [comment]
Working like a charm, I've tested all available ```@event``` (some more than others)

but I have a weird Error (probably a warning?!) :
```javascript
AddMesh.vue?73eb:106
 Uncaught TypeError: Cannot read properties of undefined (reading 'face') at Proxy.onClick 
(AddMesh.vue?73eb:106:1)
```
But the code compute well and it still run !

```vue.js
<template>
   ...
   <GLTFLoader
       url='/test-mesh/'
       @load="onCreation"
       enable-raycasting
       @click="onClick"
   >
   </GLTFLoader>
   ...
</template>
<script>
    ...
    onClick(is) {
      let color = new THREE.Color('red')
      const arrowHelper = new THREE.ArrowHelper(is[0].face.normal, is[0].point, 1, color, 1, 1);
      this.scene.add(arrowHelper)
      console.log(is[0].face) // works perfectly and arrow is added to the scene !
    },
</script>
```

If you can't recreate it on your side nevermind, its still run !
Just I've got a bit of red in my console I feel bad eheh

**Comment by LeoGrosjean** [comment]
It is really laggy compared to using :

```
window.addEventListener("pointerup", this.onClick, false);
```

>```this.onClick``` a method with my own raycasting management (not using ```enable-raycasting``` props)

> I tested with ```pointerup``` and ```click```, same result

I can show more code if needed

**Comment by LeoGrosjean** [comment]
Sorry for the missleading information, after much more testing it's kindly the same... weird I might sleep more

Thank you for this fix!

**Comment by janvorisek** [comment]
You were right! The way raycasting was implemented was not performant. `enableRaycasting` always fired raycasting on `@mouseMove` even when you didn't listen to the event. This is expensive for large models when you are only interested in `click` event.

I have moved raycasting event listeners into props - callbacks. Please replace `@click` to `:click` etc. This way raycasting works on demand - if you only provide `:onClick` function - no raycasting will be performed on mouse move as expected.

Sorry for the API change, but this way it's much more performant. Please report any issues.

It's implemented in the latest version `1.0.0-alpha-1.34`

**Comment by janvorisek** [comment]
Can I close this issue? It seems resolved.

**Comment by LeoGrosjean** [comment]
you can close it!
