### ISSUE TITLE
TrackballControls speed

### ISSUE THREAD

**Issue by LeoGrosjean** [janvorisek/drie#60]
TrackballControls speed is going faster when the window size is increased

> I've tested on both vertical and horizontal monitor

```<TrackballControls :rotate-speed="0.01" :pan-speed="0.01"/>```

**Comment by janvorisek** [comment]
I didn't know TrackballControls have `handleResize` method which is supposed to be called on canvas resize.
I have implemented it in `1.0.0-alpha-1.34`.

Please, check if it works properly, and close the issue if you have no more issues.

**Comment by LeoGrosjean** [comment]
Closed as resolved.
