### ISSUE TITLE
Gltf Mesh Order (group children) on phone missmatch

### ISSUE THREAD

**Issue by LeoGrosjean** [janvorisek/drie#96]
On phone (iphone 13 pro max using safari) :
- The chair color don't change
- The text notice bellow chair get the selected color

https://www.drie.dev/examples/eshop-product

Works fine on my desktop

**Comment by LeoGrosjean** [comment]
![image](https://user-images.githubusercontent.com/9574771/218343736-128cc9bb-5599-4821-9eb2-475c2532ae29.png)

**Comment by janvorisek** [comment]
I have confirmed the issue on both the iphone and macbook.

**Comment by janvorisek** [comment]
The issue was resolved. Please confirm on your i-phone.

**Comment by LeoGrosjean** [comment]
👌
